# examples/server-customization/config.yaml
server:
  http:
    port: 9443
    read_timeout: 15s
    write_timeout: 15s
    idle_timeout: 60s
    shutdown_timeout: 30s
    max_header_size: 1048576 # 1MB

  tls:
    enabled: true
    cert_file: "examples/server-customization/certs/server.crt"
    key_file: "examples/server-customization/certs/server.key"
    min_version: "1.2"
    prefer_server_ciphers: true
    cipher_suites:
      # TLS 1.3 cipher suites (mandatory)
      - "TLS_AES_128_GCM_SHA256"
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
      # TLS 1.2 cipher suites (backward compatibility)
      - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
      - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
      - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
      - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"

logging:
  level: info
  fields:
    environment: "dev"
    component: "server-example"

observability:
  exclude_from_logging: ["/internal/*", "/metrics"]
  exclude_from_tracing: ["/internal/*", "/metrics"]

tracing:
  endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
  sample_rate: 1.0
  propagators: ["tracecontext", "baggage"]
