# examples/quickstart/config.yaml
server:
  http:
    port: 8080
    read_timeout: 15s
    write_timeout: 15s
    shutdown_timeout: 15s

logging:
  level: info
  fields:
    environment: "dev"
    component: "todo-service"

observability:
  exclude_from_logging: ["/internal/*", "/metrics"]
  exclude_from_tracing: ["/internal/*", "/metrics"]

tracing:
  endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
  sample_rate: 1.0
  propagators: ["tracecontext", "baggage"]
